### PR TITLE
fixed vertical alignment issues

### PR DESCRIPTION
**Pull request by momolder**
Hi, 
A small fix to the css to display the ms-options correctly.
Best regards,
Mo

### CODE REVIEW

**Comment by nobleclem** [comment]
Can you clarify the case in which the alignment issue happens?

**Comment by momolder** [comment]
If you just use jquery, and the multiselect, the dropdown list is not aligned correctly with the input field.
The picture shows left before PR, right after PR. I think the actual issue is related to changes you did to the container objects as the code on your example page still uses another version without the 'ms-options'
untitled

**Comment by nobleclem** [comment]
Ok I think I see the actual problem.  However it would be nice to see if you can test it.

Instead of your fix what if you added `position: relative;` to the `.ms-options-wrap` element?

So for the css code adding the following to the beginning of the css file should do the trick
```
.ms-options-wrap {
    position: relative;
}
```

**Comment by momolder** [comment]
>```
> .ms-options-wrap {
>     position: relative;
> }
> ```
I tried that already, but then the dropdown space is already reserved before the dropdown is opened and the following HTML elements are moved in relation to the dropdown size.

**Pull request closed without merging**
