### PR TITLE
IE8 - Handle click event in entire option

### PR DESCRIPTION
**Pull request by Lwysiwyg**

### CODE REVIEW

**Comment by nobleclem** [comment]
I am not sure exactly what this is supposed to fix?  IE8 from my tests works.  Can you elaborate on this?

**Comment by Lwysiwyg** [comment]
My bad ! I did more tests and found that problem is a bit more complex that expected !! :-/

I don't want to show checkboxes, so I use option "showCheckbox", positionning it to "false"

For IE9 and more recent navigator, clicking on an item without checkbox works pretty well.
For IE8, clicking on an item doesn't work. It seems that click event isn't attached to label when checkbox is hidden.

So, issue seems to be related to line 553 :

```
if( !this.options.showCheckbox ) {
	container.find('input[id="ms-opt-'+ msCounter +'"]').hide();
}
```

I managed to hide this using specific CSS for IE8, and adding modifying some code :

```
CSS :
	.ms-checkbox-hidden-ie8 {
		height : 0px;
		width : 0px;
	}
	.ms-checkbox-hidden {
		display : none;
	}

JS - Line 450 :
if( $(this).css('display').match(/block$/) && !$(this).is('[class*="ms-checkbox-hidden"]')) {

JS - Line 553 :
container.find('input[id="ms-opt-'+ msCounter +'"]').addClass(( this._ieVersion() && (this._ieVersion() <= 8) ) ? 'ms-checkbox-hidden-ie8' : 'ms-checkbox-hidden');
```

Maybe this fix is more pertinant ? What do you think about that ?

PS : sorry my English, I'm not really fluent ;-)

**Comment by nobleclem** [comment]
Ok I see what the problem is.  Yes I should have accounted for that.  I have reworked how the showCheckbox option works.

I have removed the jquery hide() call and replaced it with an earlier addClass() to indicate the checkboxes should be hidden.  I am hiding them in a similar but more cross browser way that still allows the checkboxes to be accessed VIA keyboard and it should still pass accessibility issues.  With this change I adjusted how the hover state default is styled so that I can account for visual difference between focus on the checkbox (keyboard accessed) and selected option state.

Let me know if the update works for you.

**Comment by Lwysiwyg** [comment]
Sorry, was on holidays. Will check your fix next week at work ;-)

**Pull request closed without merging**
